language: node_js

node_js:
  - 8
  - 10

jobs:
  include:
    - stage: storybook
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - 'npm run build-storybook'
          - 'npm run deploy-storybook'

    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
